### ISSUE TITLE
Call either gtmOnSucces or gtmOnFailure exactly once every time your template is run

### ISSUE THREAD

**Issue by julianhsu8** [yugin-pro/gtm-template-variable-datalayer-validate#1]
When reviewing your template, we've noticed that `gtmOnSuccess` or `gtmOnFailure` are not always called. Calling one of these functions every time the template runs is required so that users can sequence their tags correctly. Please update your template to ensure that either `gtmOnSuccess` or `gtmOnFailure` is always called.

**Comment by yugin-pro** [comment]
> ase update your template to ensure that eit

Hi @julianhsu8 ,According to the documentation, creating templated variables does not require using such methods.
https://developers.google.com/tag-platform/tag-manager/templates
> Instead of calling data['gtmOnSuccess'] to indicate completion, variables return a value directly.
